### ISSUE TITLE
Find a collaborative online tool for sticky notes

### ISSUE THREAD

**Issue by varya** [component-driven/ds-101-workshop#2]
Our tool of choice is **Mural**

**Comment by varya** [comment]
## Requirements
* easy access for attendees:
   No registration, or easy registration
* custom board

**Comment by varya** [comment]
## Miro
* Pricing: https://miro.com/pricing/
  "Team" plan: $10 per user. We can give access to attendees for short period of time, then remove them from the team.

**Comment by varya** [comment]
## Mural
* Link: https://mural.co/
* Pricing
  * Free 30-day trial
  * $12 per member per month (billed annually)
* Template
   * None of ready-made templates responds the needs
   * Custom template can be made based on "Creative matrix" template

**Comment by varya** [comment]
## Jamboard (by Google)
* Link: https://edu.google.com/products/jamboard/?modal_active=none
* Pricing: not clear, maybe free
* Template: no pre-defined templates
* Collaboration: attendees need to have gmails

**Comment by varya** [comment]
## Figma
* Link: https://www.figma.com/
* Template: need to create your own
* UX: not trivial for non-Figma users
* Collaboration: people need to have their own accounts (but they need it for UI inventory too)

**Comment by varya** [comment]
## Bitpaper
* Link: https://www.bitpaper.io/
* Pricing: $10/month
   Complex model, there are some "calls" there.

**Comment by okonet** [comment]
We decided to pick Mural
