### ISSUE TITLE
Figure out hosting for materials

### ISSUE THREAD

**Issue by okonet** [component-driven/ds-101-workshop#6]
### Requirements

- [x] Shareable unique URLs with images / graphics
- [x] Allow linking to them from the presentation
- [ ] Maybe make exercises interactive

**Comment by varya** [comment]
We can use one of the tools from the workshop. For example, in Mural, if we choose it, it is possible to share a link.

https://app.mural.co/t/ds1014061/m/ds1014061/1585293973834/c4fcd76dd4155293f9c612e43554e5bf65cdf506

Another option could be Figma

https://www.figma.com/file/68IHG6trKOF1OBfdguelDM/Example?node-id=0%3A1

**Comment by okonet** [comment]
I've setup a sub-domain https://ds101.component-driven.io. Currently our slides are boing to be deployed to `/slides` but I can change this to root as well. My idea is to reserve `/` for attendees: instructions, materials, etc. Thoughts?

Everything is automatically deployed from `master` branch. 

For static assets there is `static` folder. We can create sub-folders as we need and put assets to share there.
